pipeline {
   agent { label 'ACE12' }
   options {
      skipDefaultCheckout(true)
   }
   stages {
      stage('Build') {
          steps {
              cleanWs()
              checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'Application']], userRemoteConfigs: [[url: "${params.GIT_REPOSITORY}"]]])
              sh '/home/iresh/iresh-s-buildscripts/ace/build.sh'
          }
      }

      stage('Upload artifact') {
          steps {
              sh '''mvn deploy:deploy-file -Durl=<maven_repo_url> -DrepositoryId=<repo_id> -Dfile=`echo *.bar` -DpomFile=pom.xml -Dpackaging=bar'''
          }
      }

      stage('Deploy') {
          steps {
              sh '/home/iresh/iresh-s-buildscripts/ace/deploy.sh TEST server1'
          }
      }
   }
}