pipeline {
   agent { label 'ACE12' }
   options {
      skipDefaultCheckout(true)
   }
   stages {
      stage('Build') {
          steps {
              cleanWs()
              checkout scm: [$class: 'GitSCM', branches: scm.branches, extensions: scm.extensions + [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'application']], userRemoteConfigs: scm.userRemoteConfigs] 
              sh '/full/path/to/build.sh "<shared_lib_directory>"'
          }
      }

      stage('Upload artifact') {
          steps {
              sh '''mvn deploy:deploy-file -Durl=<maven_repo_url> -DrepositoryId=<repo_id> -Dfile=`echo *.bar` -DpomFile=pom.xml -Dpackaging=bar'''
          }
      }

      stage('Deploy') {
          steps {
              sh '/full/path/to/deploy.sh <NodeSpec> <server>'
          }
      }
   }
}
